Repository vuejs-ar/ar.vuejs.org, pull requests merged in 2020-01, with the labels that each got.

#21 [DONE] EXAMPLES
  src/v2/examples/commits.md
  src/v2/examples/deepstream.md
  src/v2/examples/elastic-header.md
  src/v2/examples/firebase.md
  src/v2/examples/grid-component.md
  src/v2/examples/hackernews.md
  src/v2/examples/index.md
  src/v2/examples/modal.md
  src/v2/examples/select2.md
  src/v2/examples/svg.md
  src/v2/examples/themes.md
  src/v2/examples/todomvc.md
  src/v2/examples/tree-view.md
Labels: update needed

#23 [DONE] Fix the example text translation and finish join.md
  src/v2/guide/join.md
  themes/vue/layout/page.ejs
Labels: in-review

#25 [DONE]: Translating 'Unit Testing'
  src/v2/guide/unit-testing.md
Labels: approved
